logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:mysql://10.222.112.183:3306/sparks-db?serverTimezone=Australia/Sydney
    username: sparks-users
    password: sparksDB
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
server:
  port : 8089
